name: rewardsystem
description: "A rewards system for reviews and games."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8


  # 네트워크 및 API 통신
  http: ^1.0.0
  dio: ^5.0.0

  # 상태 관리
  provider: ^6.0.0

  # 로컬 저장소
  shared_preferences: ^2.0.0
  flutter_secure_storage: ^8.0.0

  # UI 관련
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.1.0

  # 유틸리티
  intl: ^0.18.0

dev_dependencies:
  url_launcher: ^6.1.12
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/